<template>
  <div class="application-page">
    <h2>{{pluginName}}</h2>
    <p class="meta">Plugin ID: {{pluginId}}</p>
    <p class="hint">
      This page is generated by <code>web-ext-kit create</code> and is ready for host route registration.
    </p>

    <section class="card">
      <h3>Host Capability Check</h3>
      <button class="inspect-btn" type="button" @click="inspectModules">Inspect host modules</button>
      <pre class="code">{{ moduleSummary }}</pre>
    </section>
  </div>
</template>

<script>
export default {
  name: '{{libName}}Page',
  data() {
    return {
      moduleSummary: ''
    }
  },
  methods: {
    inspectModules() {
      this.moduleSummary = JSON.stringify(
        {
          request: typeof (this.$host && this.$host.request),
          download: typeof (this.$host && this.$host.download),
          router: typeof (this.$host && this.$host.router),
          store: typeof (this.$host && this.$host.store),
          elementMessage: typeof this.$message
        },
        null,
        2
      )
    }
  },
  mounted() {
    this.inspectModules()
  }
}
</script>

<style scoped>
.application-page {
  padding: 16px;
  display: grid;
  gap: 14px;
}
h2 {
  margin: 0 0 8px;
  font-size: 1.25rem;
}
.meta {
  margin: 0;
  color: #64748b;
  font-size: 0.875rem;
}
.hint {
  margin-top: 12px;
  font-size: 0.8125rem;
  color: #475569;
}
.card {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 10px;
  padding: 14px 16px;
}
.card h3 {
  margin: 0 0 12px;
  font-size: 1rem;
}
.inspect-btn {
  border: 0;
  background: #0f172a;
  color: #fff;
  border-radius: 6px;
  padding: 8px 12px;
  cursor: pointer;
}
.code {
  margin: 12px 0 0;
  background: #f8fafc;
  border-radius: 8px;
  padding: 10px 12px;
  font-size: 12px;
  color: #334155;
  overflow: auto;
}
code {
  font-size: 0.9em;
  background: #e2e8f0;
  padding: 2px 6px;
  border-radius: 4px;
}
</style>
